-- Migration v31 generated: 2026-03-16
-- Goal: registrar actividad de uso en la app para análisis de conexión y carga operativa por usuario.

BEGIN;

CREATE TABLE IF NOT EXISTS public.app_user_activity_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  user_email text,
  role_code text,
  route text NOT NULL,
  event_type text NOT NULL CHECK (event_type IN ('page_view', 'heartbeat')),
  session_id text,
  client_ts timestamptz,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_app_user_activity_logs_created_at
  ON public.app_user_activity_logs (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_app_user_activity_logs_user_created_at
  ON public.app_user_activity_logs (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_app_user_activity_logs_event_type
  ON public.app_user_activity_logs (event_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_app_user_activity_logs_route
  ON public.app_user_activity_logs (route, created_at DESC);

ALTER TABLE public.app_user_activity_logs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'app_user_activity_logs'
      AND policyname = 'app_activity_select_authenticated'
  ) THEN
    CREATE POLICY app_activity_select_authenticated
      ON public.app_user_activity_logs
      FOR SELECT
      TO authenticated
      USING (auth.role() = 'authenticated');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'app_user_activity_logs'
      AND policyname = 'app_activity_insert_own_user'
  ) THEN
    CREATE POLICY app_activity_insert_own_user
      ON public.app_user_activity_logs
      FOR INSERT
      TO authenticated
      WITH CHECK (
        auth.role() = 'authenticated'
        AND auth.uid() = user_id
      );
  END IF;
END $$;

GRANT SELECT, INSERT ON public.app_user_activity_logs TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.app_user_activity_logs_id_seq TO authenticated;

COMMIT;
